name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"
      - run: cpanm --installdeps --notest .
      - run: .cicd/linux+self+cicd.sh

