name: CI

on:
  push:
  pull_request:

jobs:
  dist:
    runs-on: ubuntu-latest
    container:
      image: perl:5.40-bookworm
    steps:
      - uses: actions/checkout@v6
      - name: Fix safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: perl -V
        run: perl -V
      - uses: Getty/p5-dist-zilla-pluginbundle-author-getty/.github/actions/dzil-test@main

  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Getty/simpici/action@main
        env:
          CICD_REGISTRY: docker.io
          CICD_REGISTRY_USER: raudssus
          CICD_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          CICD_IMAGE_REPOSITORY: raudssus/simpici
          CICD_PUBLISH_IMAGE: ${{ github.event_name != 'pull_request' }}

  ghcr:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/simpici.yml
